// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApArticleConfig = "ap_article_config"

// ApArticleConfig APP已发布文章配置表
type ApArticleConfig struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ArticleID *int64 `gorm:"column:article_id;type:bigint unsigned;comment:文章ID" json:"articleId,string"`       // 文章ID
	IsComment *int32 `gorm:"column:is_comment;type:tinyint unsigned;comment:是否可评论" json:"isComment"`            // 是否可评论
	IsForward *int32 `gorm:"column:is_forward;type:tinyint unsigned;comment:是否转发" json:"isForward"`             // 是否转发
	IsDown    *int32 `gorm:"column:is_down;type:tinyint unsigned;comment:是否下架" json:"isDown"`                   // 是否下架
	IsDelete  *int32 `gorm:"column:is_delete;type:tinyint unsigned;comment:是否已删除" json:"isDelete"`              // 是否已删除
}

// TableName ApArticleConfig's table name
func (*ApArticleConfig) TableName() string {
	return TableNameApArticleConfig
}
