// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApArticleContent = "ap_article_content"

// ApArticleContent APP已发布文章内容表
type ApArticleContent struct {
	ID        int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ArticleID *int64  `gorm:"column:article_id;type:bigint unsigned;comment:文章ID" json:"articleId,string"`       // 文章ID
	Content   *string `gorm:"column:content;type:longtext;comment:文章内容" json:"content"`                          // 文章内容
}

// TableName ApArticleContent's table name
func (*ApArticleContent) TableName() string {
	return TableNameApArticleContent
}
