// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApAuthor = "ap_author"

// ApAuthor APP文章作者信息表
type ApAuthor struct {
	ID   int32   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name *string `gorm:"column:name;type:varchar(20);comment:作者名称" json:"name"`                          // 作者名称
	/*
		0 爬取数据
		            1 签约合作商
		            2 平台自媒体人

	*/
	Type        *int32     `gorm:"column:type;type:tinyint unsigned;comment:0 爬取数据\n            1 签约合作商\n            2 平台自媒体人\n" json:"type"`
	UserID      *int32     `gorm:"column:user_id;type:int unsigned;comment:社交账号ID" json:"userId,string"`     // 社交账号ID
	CreatedTime *time.Time `gorm:"column:created_time;type:datetime;comment:创建时间" json:"createdTime"`        // 创建时间
	WmUserID    *int32     `gorm:"column:wm_user_id;type:int unsigned;comment:自媒体账号" json:"wmUserId,string"` // 自媒体账号
}

// TableName ApAuthor's table name
func (*ApAuthor) TableName() string {
	return TableNameApAuthor
}
