// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApCollection = "ap_collection"

// ApCollection APP收藏信息表
type ApCollection struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	EntryID   *int32 `gorm:"column:entry_id;type:int unsigned;comment:实体ID" json:"entryId,string"`        // 实体ID
	ArticleID *int64 `gorm:"column:article_id;type:bigint unsigned;comment:文章ID" json:"articleId,string"` // 文章ID
	/*
		点赞内容类型
		            0文章
		            1动态
	*/
	Type           *int32     `gorm:"column:type;type:tinyint unsigned;comment:点赞内容类型\n            0文章\n            1动态" json:"type"`
	CollectionTime *time.Time `gorm:"column:collection_time;type:datetime;comment:创建时间" json:"collectionTime"` // 创建时间
	PublishedTime  *time.Time `gorm:"column:published_time;type:datetime;comment:发布时间" json:"publishedTime"`   // 发布时间
}

// TableName ApCollection's table name
func (*ApCollection) TableName() string {
	return TableNameApCollection
}
