// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"fmt"
	"strings"
	"time"
)

const TableNameDgsGeneralFailure = "dgs_general_failures"

// DgsGeneralFailure mapped from table <dgs_general_failures>

type Array []string

// Scan 从数据库中读取出来
func (arr *Array) Scan(value interface{}) error {
	//data, ok := value.([]byte)

	valueStr := fmt.Sprintf("%v", value)

	//if !ok {
	//	return errors.New(fmt.Sprintf("解析失败: %v %T", value, value))
	//}

	*arr = strings.Split(valueStr, "|")
	return nil
}

// Value 存入数据库
func (arr Array) Value() (driver.Value, error) {
	return strings.Join(arr, "|"), nil
}
type DgsGeneralFailure struct {
	ID                   *int32     `gorm:"column:id;type:integer" json:"id"`
	AlarmTitle           string     `gorm:"column:alarm_title;type:character varying;not null;comment:告警标题" json:"alarmTitle"`                    // 告警标题
	AlarmHandle          string     `gorm:"column:alarm_handle;type:character varying;not null;comment:告警解决方案" json:"alarmHandle"`                // 告警解决方案
	AlarmKeyword         *string    `gorm:"column:alarm_keyword;type:character varying;comment:告警关键字" json:"alarmKeyword"`                        // 告警关键字
	AlarmType            *string    `gorm:"column:alarm_type;type:character varying;comment:告警类型" json:"alarmType"`                               // 告警类型
	AlarmCreaterID       *int32     `gorm:"column:alarm_creater_id;type:integer;comment:创建人ID" json:"alarmCreaterId,string"`                      // 创建人ID
	CreateTime           *time.Time `gorm:"column:create_time;type:datetime(0);autoUpdateTime;comment:创建时间" json:"createTime"`                    // 创建时间
	UpdateTime           *time.Time `gorm:"column:update_time;type:datetime(0);autoUpdateTime;comment:更新时间" json:"updateTime"`                    // 更新时间
	AlarmSystemInfluence *string    `gorm:"column:alarm_system_influence;type:character varying(255);comment:对系统的影响" json:"alarmSystemInfluence"` // 对系统的影响
	AlarmDetail          *string    `gorm:"column:alarm_detail;type:character varying(15000);comment:告警详情" json:"alarmDetail"`                     // 告警详情
	AlarmPossibleReasons Array    `gorm:"column:alarm_possible_reasons;type:character varying(255);comment:告警可能原因" json:"alarmPossibleReasons"` // 告警可能原因
}

// TableName DgsGeneralFailure's table name
func (*DgsGeneralFailure) TableName() string {
	return TableNameDgsGeneralFailure
}
