// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZbDream = "zb_dream"

// ZbDream 周公解梦
type ZbDream struct {
	ID      int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title   string `gorm:"column:title;type:varchar(50);not null" json:"title"`
	Message string `gorm:"column:message;type:text;not null" json:"message"`
	Biglx   string `gorm:"column:biglx;type:varchar(20);not null" json:"biglx"`
	Smalllx string `gorm:"column:smalllx;type:varchar(20);not null" json:"smalllx"`
	Zm      string `gorm:"column:zm;type:varchar(3);not null" json:"zm"`
}

// TableName ZbDream's table name
func (*ZbDream) TableName() string {
	return TableNameZbDream
}
