// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"AndroidToolServer-Go/model"
)

func newApArticleContent(db *gorm.DB, opts ...gen.DOOption) apArticleContent {
	_apArticleContent := apArticleContent{}

	_apArticleContent.apArticleContentDo.UseDB(db, opts...)
	_apArticleContent.apArticleContentDo.UseModel(&model.ApArticleContent{})

	tableName := _apArticleContent.apArticleContentDo.TableName()
	_apArticleContent.ALL = field.NewAsterisk(tableName)
	_apArticleContent.ID = field.NewInt64(tableName, "id")
	_apArticleContent.ArticleID = field.NewInt64(tableName, "article_id")
	_apArticleContent.Content = field.NewString(tableName, "content")

	_apArticleContent.fillFieldMap()

	return _apArticleContent
}

// apArticleContent APP已发布文章内容表
type apArticleContent struct {
	apArticleContentDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	ArticleID field.Int64  // 文章ID
	Content   field.String // 文章内容

	fieldMap map[string]field.Expr
}

func (a apArticleContent) Table(newTableName string) *apArticleContent {
	a.apArticleContentDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a apArticleContent) As(alias string) *apArticleContent {
	a.apArticleContentDo.DO = *(a.apArticleContentDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *apArticleContent) updateTableName(table string) *apArticleContent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ArticleID = field.NewInt64(table, "article_id")
	a.Content = field.NewString(table, "content")

	a.fillFieldMap()

	return a
}

func (a *apArticleContent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *apArticleContent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["id"] = a.ID
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["content"] = a.Content
}

func (a apArticleContent) clone(db *gorm.DB) apArticleContent {
	a.apArticleContentDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a apArticleContent) replaceDB(db *gorm.DB) apArticleContent {
	a.apArticleContentDo.ReplaceDB(db)
	return a
}

type apArticleContentDo struct{ gen.DO }

func (a apArticleContentDo) Debug() *apArticleContentDo {
	return a.withDO(a.DO.Debug())
}

func (a apArticleContentDo) WithContext(ctx context.Context) *apArticleContentDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apArticleContentDo) ReadDB() *apArticleContentDo {
	return a.Clauses(dbresolver.Read)
}

func (a apArticleContentDo) WriteDB() *apArticleContentDo {
	return a.Clauses(dbresolver.Write)
}

func (a apArticleContentDo) Session(config *gorm.Session) *apArticleContentDo {
	return a.withDO(a.DO.Session(config))
}

func (a apArticleContentDo) Clauses(conds ...clause.Expression) *apArticleContentDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apArticleContentDo) Returning(value interface{}, columns ...string) *apArticleContentDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apArticleContentDo) Not(conds ...gen.Condition) *apArticleContentDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apArticleContentDo) Or(conds ...gen.Condition) *apArticleContentDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apArticleContentDo) Select(conds ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apArticleContentDo) Where(conds ...gen.Condition) *apArticleContentDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apArticleContentDo) Order(conds ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apArticleContentDo) Distinct(cols ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apArticleContentDo) Omit(cols ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apArticleContentDo) Join(table schema.Tabler, on ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apArticleContentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apArticleContentDo) RightJoin(table schema.Tabler, on ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apArticleContentDo) Group(cols ...field.Expr) *apArticleContentDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apArticleContentDo) Having(conds ...gen.Condition) *apArticleContentDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apArticleContentDo) Limit(limit int) *apArticleContentDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apArticleContentDo) Offset(offset int) *apArticleContentDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apArticleContentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *apArticleContentDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apArticleContentDo) Unscoped() *apArticleContentDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apArticleContentDo) Create(values ...*model.ApArticleContent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apArticleContentDo) CreateInBatches(values []*model.ApArticleContent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apArticleContentDo) Save(values ...*model.ApArticleContent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apArticleContentDo) First() (*model.ApArticleContent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApArticleContent), nil
	}
}

func (a apArticleContentDo) Take() (*model.ApArticleContent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApArticleContent), nil
	}
}

func (a apArticleContentDo) Last() (*model.ApArticleContent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApArticleContent), nil
	}
}

func (a apArticleContentDo) Find() ([]*model.ApArticleContent, error) {
	result, err := a.DO.Find()
	return result.([]*model.ApArticleContent), err
}

func (a apArticleContentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ApArticleContent, err error) {
	buf := make([]*model.ApArticleContent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apArticleContentDo) FindInBatches(result *[]*model.ApArticleContent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apArticleContentDo) Attrs(attrs ...field.AssignExpr) *apArticleContentDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apArticleContentDo) Assign(attrs ...field.AssignExpr) *apArticleContentDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apArticleContentDo) Joins(fields ...field.RelationField) *apArticleContentDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apArticleContentDo) Preload(fields ...field.RelationField) *apArticleContentDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apArticleContentDo) FirstOrInit() (*model.ApArticleContent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApArticleContent), nil
	}
}

func (a apArticleContentDo) FirstOrCreate() (*model.ApArticleContent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApArticleContent), nil
	}
}

func (a apArticleContentDo) FindByPage(offset int, limit int) (result []*model.ApArticleContent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apArticleContentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apArticleContentDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apArticleContentDo) Delete(models ...*model.ApArticleContent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apArticleContentDo) withDO(do gen.Dao) *apArticleContentDo {
	a.DO = *do.(*gen.DO)
	return a
}
